import 'dart:math' as math;

import 'package:flutter/material.dart';

import '../../domain/models/dice_result.dart';
import 'dice_motion_profile.dart';
import 'dice_skin.dart';
import 'ludo_dice_painter.dart';
import 'rive_dice_asset.dart';
import 'rive_dice_renderer.dart';

/// Displays one responsive and animated Ludo dice.
///
/// The owning application supplies the logical result, availability, rolling
/// state, and callbacks. The logical result is generated before animation and
/// published only after the configured presentation finishes.
///
/// The Rive renderer is presentation-only. It never generates results,
/// calculates legal moves, releases tokens, or grants additional turns.
class LudoDice extends StatefulWidget {
  /// Creates an interaction-ready animated dice.
  const LudoDice({
    required this.result,
    required this.dimension,
    this.isRolling = false,
    this.isEnabled = true,
    this.skin = DiceSkin.classicIvory,
    this.motionProfile = DiceMotionProfile.classicRoll,
    this.riveAsset = RiveDiceAsset.classic3d,
    this.useRiveRenderer = true,
    this.onRollRequested,
    this.onRollAnimationCompleted,
    super.key,
  }) : assert(dimension > 0, 'Dice dimension must be greater than zero.');

  /// Key identifying the isolated dice repaint boundary.
  static const Key repaintBoundaryKey = ValueKey<String>(
    'ludo-dice-repaint-boundary',
  );

  /// Logical result generated by the authoritative caller.
  final DiceResult result;

  /// Width and height of the complete dice-control area.
  final double dimension;

  /// Whether the caller wants the roll animation displayed.
  final bool isRolling;

  /// Whether the authoritative caller permits a roll request.
  final bool isEnabled;

  /// Cosmetic configuration used by the procedural fallback.
  final DiceSkin skin;

  /// Motion configuration used by the procedural fallback.
  final DiceMotionProfile motionProfile;

  /// Rive cosmetic and animation configuration.
  final RiveDiceAsset riveAsset;

  /// Whether the production Rive renderer should be used.
  ///
  /// Tests may disable it to exercise deterministic procedural fallback
  /// behavior without initializing the platform Rive runtime.
  final bool useRiveRenderer;

  /// Optional callback requesting a new logical result.
  final VoidCallback? onRollRequested;

  /// Callback invoked after the supplied result is visually revealed.
  final ValueChanged<DiceResult>? onRollAnimationCompleted;

  @override
  State<LudoDice> createState() => _LudoDiceState();
}

/// Owns presentation sequencing for one dice roll.
class _LudoDiceState extends State<LudoDice>
    with SingleTickerProviderStateMixin {
  late final AnimationController _rollController;
  late DiceResult _displayedResult;

  int _playbackSequence = 0;
  bool _animationsDisabled = false;
  bool _completionReported = false;
  bool _initialAnimationSynchronized = false;

  /// Duration associated with the active visual renderer.
  Duration get _activeDuration {
    if (widget.useRiveRenderer) {
      return widget.riveAsset.playbackDuration;
    }

    return widget.motionProfile.duration;
  }

  @override
  void initState() {
    super.initState();

    // Keep the resting value separate from the pending logical value so the
    // next result cannot become available to consumers before landing.
    _displayedResult = widget.result;

    _rollController = AnimationController(
      duration: _activeDuration,
      vsync: this,
    )..addStatusListener(_handleAnimationStatus);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    final animationsDisabled =
        MediaQuery.maybeOf(context)?.disableAnimations ?? false;
    final accessibilityChanged = animationsDisabled != _animationsDisabled;

    _animationsDisabled = animationsDisabled;

    if (!_initialAnimationSynchronized) {
      _initialAnimationSynchronized = true;

      if (widget.isRolling) {
        _startRollAnimation();
      }

      return;
    }

    if (accessibilityChanged && widget.isRolling) {
      _startRollAnimation();
    }
  }

  @override
  void didUpdateWidget(covariant LudoDice oldWidget) {
    super.didUpdateWidget(oldWidget);

    final durationChanged =
        oldWidget.motionProfile.duration != widget.motionProfile.duration ||
        oldWidget.riveAsset.playbackDuration !=
            widget.riveAsset.playbackDuration ||
        oldWidget.useRiveRenderer != widget.useRiveRenderer;

    if (durationChanged) {
      _rollController.duration = _activeDuration;
    }

    final rollStarted = widget.isRolling && !oldWidget.isRolling;
    final rollingResultChanged =
        widget.isRolling && oldWidget.result != widget.result;
    final rollingAssetChanged =
        widget.isRolling && oldWidget.riveAsset != widget.riveAsset;

    if (rollStarted) {
      // Preserve the previously displayed resting result while the Rive
      // renderer receives the already-generated pending result.
      _displayedResult = oldWidget.result;
      _startRollAnimation();
      return;
    }

    if (rollingResultChanged || rollingAssetChanged) {
      // Restart presentation when the authoritative owner replaces the
      // pending result or active cosmetic during a rolling sequence.
      _startRollAnimation();
      return;
    }

    if (!widget.isRolling) {
      _rollController.stop();
      _rollController.value = 1;

      // Direct changes outside a rolling sequence display immediately.
      _displayedResult = widget.result;
    }
  }

  /// Starts presentation for an already-generated logical result.
  void _startRollAnimation() {
    _completionReported = false;
    _playbackSequence++;

    if (_animationsDisabled) {
      _rollController.stop();
      _rollController.value = 1;

      // Reduced-motion mode skips visual rolling while preserving the
      // asynchronous completion boundary.
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (!mounted || !widget.isRolling || _completionReported) {
          return;
        }

        _completeRollPresentation();
      });

      return;
    }

    _rollController.forward(from: 0);
  }

  /// Detects the end of the configured presentation duration.
  void _handleAnimationStatus(AnimationStatus status) {
    if (status != AnimationStatus.completed ||
        !widget.isRolling ||
        _completionReported) {
      return;
    }

    _completeRollPresentation();
  }

  /// Reveals and publishes the exact logical result supplied by the caller.
  void _completeRollPresentation() {
    _completionReported = true;

    if (_displayedResult != widget.result) {
      setState(() {
        _displayedResult = widget.result;
      });
    }

    widget.onRollAnimationCompleted?.call(widget.result);
  }

  /// Requests a new roll only when permitted by the owning state.
  void _handleRollRequested() {
    if (!widget.isEnabled ||
        widget.isRolling ||
        widget.onRollRequested == null) {
      return;
    }

    widget.onRollRequested!();
  }

  /// Returns deterministic temporary faces for the procedural fallback.
  ///
  /// These temporary values never leave the presentation layer.
  DiceResult _visualResultFor(double progress) {
    if (!widget.isRolling || progress >= 1) {
      return _displayedResult;
    }

    final visualFace =
        ((progress *
                    DiceResult.faceCount *
                    widget.motionProfile.temporaryFaceCycles)
                .floor() %
            DiceResult.faceCount) +
        DiceResult.minimumValue;

    return DiceResult(visualFace);
  }

  /// Returns the scale used by the procedural fallback during rolling.
  double _rollingScaleFor(double progress) {
    if (!widget.isRolling || progress <= 0 || progress >= 1) {
      return widget.motionProfile.restingScale;
    }

    final scaleEnvelope = math
        .pow(math.sin(progress * math.pi).clamp(0.0, 1.0), 0.72)
        .toDouble();

    final scaleRange =
        widget.motionProfile.maximumRollingScale -
        widget.motionProfile.restingScale;

    return widget.motionProfile.restingScale + scaleRange * scaleEnvelope;
  }

  /// Creates fallback-only lift, bounce, scale, and impact deformation.
  ///
  /// No outer transform is applied to the Rive renderer because the Rive
  /// timelines already contain their own three-dimensional motion.
  Matrix4 _fallbackMotionTransform(double progress) {
    if (progress <= 0 || progress >= 1) {
      return Matrix4.identity();
    }

    final profile = widget.motionProfile;

    final verticalLift =
        math.sin(progress * math.pi) * widget.dimension * profile.liftFactor;

    final landingProgress = progress < 0.68 ? 0.0 : (progress - 0.68) / 0.32;

    final landingBounce = landingProgress == 0
        ? 0.0
        : math.sin(landingProgress * math.pi * 2).abs() *
              (1 - landingProgress) *
              widget.dimension *
              profile.bounceFactor;

    final impactProgress = progress < 0.88 ? 0.0 : (progress - 0.88) / 0.12;

    final impact = impactProgress == 0
        ? 0.0
        : math.sin(impactProgress * math.pi);

    final physicalScale = _rollingScaleFor(progress);
    final horizontalScale =
        physicalScale * (1 + impact * profile.impactSquashFactor * 0.70);
    final verticalScale =
        physicalScale * (1 - impact * profile.impactSquashFactor);

    return Matrix4.identity()
      ..translateByDouble(0, -verticalLift - landingBounce, 0, 1)
      ..scaleByDouble(horizontalScale, verticalScale, 1, 1);
  }

  /// Builds the existing procedural renderer as a fallback.
  Widget _buildProceduralFallback() {
    return AnimatedBuilder(
      animation: _rollController,
      builder: (context, child) {
        final progress = _rollController.value;
        final visualResult = _visualResultFor(progress);

        return Transform(
          alignment: Alignment.center,
          transform: _fallbackMotionTransform(progress),
          child: CustomPaint(
            painter: LudoDicePainter(
              result: visualResult,
              skin: widget.skin,
              rollProgress: progress,
              isRolling: widget.isRolling,
              rotationCount: widget.motionProfile.rotationCount,
              perspective: widget.motionProfile.perspective,
            ),
          ),
        );
      },
    );
  }

  /// Builds either the configured Rive cosmetic or its fallback.
  Widget _buildDiceVisual() {
    final proceduralFallback = _buildProceduralFallback();

    if (!widget.useRiveRenderer || _animationsDisabled) {
      return proceduralFallback;
    }

    // While rolling, the Rive renderer receives the pending logical result so
    // it can select Roll 1 through Roll 6. The result is still not published to
    // consumers until _completeRollPresentation executes.
    final visualResult = widget.isRolling ? widget.result : _displayedResult;

    return RiveDiceRenderer(
      result: visualResult,
      dimension: widget.dimension,
      playbackSequence: _playbackSequence,
      asset: widget.riveAsset,
      fallback: proceduralFallback,
    );
  }

  @override
  void dispose() {
    _rollController
      ..removeStatusListener(_handleAnimationStatus)
      ..dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final canRequestRoll =
        widget.isEnabled && !widget.isRolling && widget.onRollRequested != null;

    return Semantics(
      label: 'Ludo dice',
      value: widget.isRolling ? 'Rolling' : 'Result ${_displayedResult.value}',
      button: widget.onRollRequested != null,
      enabled: canRequestRoll,
      liveRegion: !widget.isRolling,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        excludeFromSemantics: true,
        onTap: canRequestRoll ? _handleRollRequested : null,
        child: RepaintBoundary(
          key: LudoDice.repaintBoundaryKey,
          child: SizedBox.square(
            dimension: widget.dimension,
            child: _buildDiceVisual(),
          ),
        ),
      ),
    );
  }
}
