import 'package:flutter/material.dart';
import 'package:rive/rive.dart' as rive;

import '../../domain/models/dice_result.dart';
import 'rive_dice_asset.dart';

/// Renders one result-specific animation from a configured Rive dice asset.
///
/// The caller supplies the already-generated logical [result]. This renderer
/// selects and displays only the corresponding visual animation.
///
/// The renderer remains paused for playback sequence zero. This prevents the
/// initial dice animation from automatically running when the game screen is
/// first opened.
///
/// One painter is retained for the complete playback sequence. Reusing the
/// painter prevents ordinary Flutter rebuilds from restarting the animation.
///
/// This renderer never generates dice values, determines move legality,
/// releases tokens, grants additional turns, or owns game state.
class RiveDiceRenderer extends StatefulWidget {
  /// Creates a reusable Rive-backed dice renderer.
  const RiveDiceRenderer({
    required this.result,
    required this.dimension,
    required this.playbackSequence,
    required this.fallback,
    this.asset = RiveDiceAsset.classic3d,
    super.key,
  }) : assert(dimension > 0, 'Dice dimension must be greater than zero.'),
       assert(playbackSequence >= 0, 'Playback sequence must not be negative.');

  /// Key identifying the clipped visible dice viewport.
  static const Key viewportKey = ValueKey<String>(
    'rive-dice-renderer-viewport',
  );

  /// Key identifying the scaled Rive artwork.
  static const Key contentKey = ValueKey<String>('rive-dice-renderer-content');

  /// Logical result generated by the authoritative caller.
  final DiceResult result;

  /// Width and height of the fixed visible dice viewport.
  final double dimension;

  /// Identity of the current visual playback.
  ///
  /// Sequence zero represents the initial resting presentation. Positive
  /// values represent user-requested rolls.
  final int playbackSequence;

  /// Asset-specific Rive rendering configuration.
  final RiveDiceAsset asset;

  /// Presentation shown while the asset loads or when loading fails.
  final Widget fallback;

  @override
  State<RiveDiceRenderer> createState() => _RiveDiceRendererState();
}

/// Retains the Rive loader and painter across ordinary Flutter rebuilds.
class _RiveDiceRendererState extends State<RiveDiceRenderer> {
  late rive.FileLoader _fileLoader;
  late rive.ArtboardPainter _animationPainter;

  @override
  void initState() {
    super.initState();

    _fileLoader = _createFileLoader();
    _animationPainter = _createAnimationPainter();
  }

  @override
  void didUpdateWidget(covariant RiveDiceRenderer oldWidget) {
    super.didUpdateWidget(oldWidget);

    final assetFileChanged =
        oldWidget.asset.assetPath != widget.asset.assetPath;

    final oldAnimationName = oldWidget.asset.animationNameFor(oldWidget.result);
    final newAnimationName = widget.asset.animationNameFor(widget.result);

    final playbackChanged =
        oldWidget.playbackSequence != widget.playbackSequence ||
        oldWidget.asset.id != widget.asset.id ||
        oldAnimationName != newAnimationName;

    if (assetFileChanged) {
      _fileLoader.dispose();
      _fileLoader = _createFileLoader();
    }

    // A new painter is required only for a genuinely new playback. Creating a
    // painter during every build would restart the same Rive animation.
    if (playbackChanged) {
      _animationPainter.dispose();
      _animationPainter = _createAnimationPainter();
    }
  }

  /// Creates a loader for the currently selected Rive cosmetic.
  rive.FileLoader _createFileLoader() {
    return rive.FileLoader.fromAsset(
      widget.asset.assetPath,
      riveFactory: rive.Factory.rive,
    );
  }

  /// Creates one animation painter for the current playback sequence.
  rive.ArtboardPainter _createAnimationPainter() {
    final animationName = widget.asset.animationNameFor(widget.result);

    return rive.SingleAnimationPainter(
      animationName,
      fit: rive.Fit.contain,
      alignment: widget.asset.alignment,
    );
  }

  @override
  void dispose() {
    _animationPainter.dispose();
    _fileLoader.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final animationName = widget.asset.animationNameFor(widget.result);

    final playbackKey = ValueKey<String>(
      '${widget.asset.id}:'
      '$animationName:'
      '${widget.playbackSequence}',
    );

    // Sequence zero is the initial screen state and must remain paused.
    final shouldAdvanceAnimation = widget.playbackSequence > 0;

    return SizedBox.square(
      dimension: widget.dimension,
      child: ClipRect(
        key: RiveDiceRenderer.viewportKey,
        child: Transform.scale(
          key: RiveDiceRenderer.contentKey,
          scale: widget.asset.contentScale,
          alignment: widget.asset.alignment,
          child: rive.RiveWidgetBuilder(
            key: ValueKey<String>('rive-loader:${widget.asset.id}'),
            fileLoader: _fileLoader,
            artboardSelector: rive.ArtboardSelector.byName(
              widget.asset.artboardName,
            ),
            builder: (context, state) {
              return switch (state) {
                rive.RiveLoading() => widget.fallback,
                rive.RiveFailed() => widget.fallback,
                rive.RiveLoaded() => TickerMode(
                  enabled: shouldAdvanceAnimation,
                  child: rive.RiveFileWidget(
                    key: playbackKey,
                    file: state.file,
                    artboardName: widget.asset.artboardName,
                    painter: _animationPainter,
                  ),
                ),
              };
            },
          ),
        ),
      ),
    );
  }
}
